export const FETCH_TABLE_SUCCESS = "FETCH_TABLE_SUCCESS"

export const ADD_NEW_WORD_SUCCESS = "ADD_NEW_WORD_SUCCESS"
export const ADD_NEW_WORD_ALERT_CLOSE = "ADD_NEW_WORD_ALERT_CLOSE"

export const DELETE_TABLE_ITEM_START = "DELETE_TABLE_ITEM_START"
export const DELETE_TABLE_ITEM = "DELETE_TABLE_ITEM"

export const EDIT_WORD_SUCCESS = "EDIT_WORD_SUCCESS"
export const EDIT_WORD_ALERT_CLOSE = "EDIT_WORD_ALERT_CLOSE"

export const CHANGE_ROLE_START = "CHANGE_ROLE_START"
export const CHANGE_ROLE_SUCCESS = "CHANGE_ROLE_SUCCESS"
export const CHOICE_ROLE_SUCCESS = "CHOICE_ROLE_SUCCESS"
export const FETCH_NAV_SUCCESS = "FETCH_NAV_SUCCESS"

export const FETCH_EDIT_INPUTS_DATA_SUCCESS = "FETCH_EDIT_INPUTS_DATA_SUCCESS"